name=ICM20602_ESP32
version=1.0.0
author=huy.y52 (tiktok)
maintainer=
sentence=ICM20602 6-axis IMU driver for ESP32 (I2C and SPI)
paragraph=ESP32 optimized ICM20602 library with I2C and SPI support, calibration, temperature reading and low-pass filter.
category=Sensors
url=
architectures=esp32
includes=ICM20602.h
